baseURL = "https://dziugasnaimavicius.github.io/"
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  assets.disableFingerprinting = true